name: ay_khedma
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  go_router: ^10.1.1
  http: ^0.13.6
  get: ^4.6.5
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  fonts:
    - family: Kohinoor Arabic
      fonts:
        - asset: assets/fonts/Kohinoor Arabic Regular.ttf